#!/usr/bin/env sh

INC="INCLUDE"
NAME=$(hostname -s)
TIME="`date +%Y%m%d-%H%M`"
export TZ="EST5EDT"
export PATH=$PATH:$(dirname $0)

[ -z "$INC" ] && echo "nothing in \$INC" && exit 1

echo "creating new snapshot: $NAME:$TIME"

tarsnap-run --print-stats \
  --checkpoint-bytes 4194304 \
  -c -f "$NAME:$TIME" $* \
  "$INC"
