#!/usr/bin/env sh

NAME=$(hostname -s)
TIME="`date +%Y%m%d-%H%M`"
export PATH=$PATH:$(dirname $0)

[ -z "$INCLUDE" ] && echo "nothing in \$INCLUDE" && exit 1

echo "creating new snapshot: $NAME:$TIME"

tarsnap-run --print-stats \
  --checkpoint-bytes 4194304 \
  -c -f "$NAME:$TIME" $* \
  "$INCLUDE"
